### ISSUE TITLE
项目不能clone，报错

### ISSUE THREAD

**Issue by icnz** [doublechaintech/scm-biz-suite#14]
Cloning into '/github/scm-biz-suite'...
remote: Enumerating objects: 83, done.        
remote: Counting objects: 100% (83/83), done.        
remote: Compressing objects: 100% (67/67), done.        
remote: Total 32144 (delta 44), reused 39 (delta 16), pack-reused 32061         
Receiving objects: 100% (32144/32144), 37.06 MiB | 733.00 KiB/s, done.          
Resolving deltas: 100% (29806/29806), done.                                     
**error: invalid path 'bizcore/.settings/org.eclipse.jdt.core.prefs '**
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Would you like to retry cloning scm-biz-suite?
---
查了下问题说在：
git上的项目问题路径文件夹末尾包含一个空格，但是在Windows中无法创建末尾包含空格的目录。

**Comment by philipgreat** [comment]
我已经删除了，你再测试下呢？

**Comment by philipgreat** [comment]
没问题了，关闭。
