### ISSUE TITLE
登陆不上去

### ISSUE THREAD

**Issue by fdzklb** [doublechaintech/scm-biz-suite#15]
密码错误

**Comment by philipgreat** [comment]
刚刚测试过， 是可以的
https://demo.doublechaintech.com/admin/retailscm/
1390000001/admin123

**Comment by fdzklb** [comment]
![image](https://user-images.githubusercontent.com/49522583/87502782-1a2ffa00-c695-11ea-8177-cb5bf1671630.png)

**Comment by philipgreat** [comment]
具体密码是什么？

**Comment by fdzklb** [comment]
账户：1390000001
密码：admin123
是不是网络问题，你是内网？

**Comment by philipgreat** [comment]
你登录的是生鲜供应链，我看看。

**Comment by fdzklb** [comment]
![image](https://user-images.githubusercontent.com/49522583/87502920-81e64500-c695-11ea-9b68-86c9df9d204a.png)

**Comment by fdzklb** [comment]
![image](https://user-images.githubusercontent.com/49522583/87502960-9e827d00-c695-11ea-95cb-79d3300a9aa0.png)

**Comment by fdzklb** [comment]
https://demo.doublechaintech.com/admin/retailscm/#/

**Comment by philipgreat** [comment]
![Screen Shot 2020-07-15 at 12 21 49](https://user-images.githubusercontent.com/11522066/87503085-ddb0ce00-c695-11ea-96fa-ff10f258de03.jpg)

截图上面有密码。
你加我微信我看看 philip-ai

**Comment by jarryscript** [comment]
> 账户：1390000001
> 密码：admin123
> 是不是网络问题，你是内网？

账户 少一位

**Comment by fdzklb** [comment]
![image](https://user-images.githubusercontent.com/49522583/87503248-50ba4480-c696-11ea-81f9-130956b299d0.png)

**Comment by fdzklb** [comment]
6个0也不行

**Comment by philipgreat** [comment]
7个0，手机号

**Comment by fdzklb** [comment]
都不行

**Comment by fdzklb** [comment]
也加不了你，‘对方被加太频繁，请稍后再试’。
