### ISSUE TITLE
数据中台的默认密码无法登陆

### ISSUE THREAD

**Issue by seanlee928** [doublechaintech/scm-biz-suite#16]
无法登陆，是否默认密码被修改？

**Comment by philipgreat** [comment]
我重新上传了sql文件，试试最新的。




| |
Philip Zhang
|
|
philip_chang@163.com
|
签名由网易邮箱大师定制


在2020年08月2日 00:00，sean<notifications@github.com> 写道：

无法登陆，是否默认密码被修改？

**Comment by philipgreat** [comment]
已经修复

**Comment by wangshuo3545** [comment]
收到，谢谢🙏




| |
wangshuo3545
|
|
邮箱：wangshuo3545@163.com
|
在2020年08月06日 15:06，Philip Z 写道：

Closed #16.
