### ISSUE TITLE
项目里用来防止并发的synchronized看起来并不能起到应有的作用

### ISSUE THREAD

**Issue by xiaodongzhang97** [doublechaintech/scm-biz-suite#17]
例如在[RetailStoreCountryCenterManagerImpl.java#addAccountSet](https://github.com/doublechaintech/scm-biz-suite/blob/c4751e198b785aa681007ea8fe96fa66e3e8b70b/bizcore/WEB-INF/retailscm_core_src/com/doublechaintech/retailscm/retailstorecountrycenter/RetailStoreCountryCenterManagerImpl.java#L3342)里有这么一段代码，看起来是想防止并发创建帐套，但是每次retailStoreCountryCenter都是被重新从数据库读进来的，两个线程读到的都不是同一对象，所以这个synchronized似乎是完全没用的。
```java
RetailStoreCountryCenter retailStoreCountryCenter = loadRetailStoreCountryCenter(userContext, retailStoreCountryCenterId, emptyOptions());
		synchronized(retailStoreCountryCenter){
			//Will be good when the retailStoreCountryCenter loaded from this JVM process cache.
			//Also good when there is a RAM based DAO implementation
			retailStoreCountryCenter.addAccountSet( accountSet );
			retailStoreCountryCenter = saveRetailStoreCountryCenter(userContext, retailStoreCountryCenter, tokens().withAccountSetList().done());
			
			accountSetManagerOf(userContext).onNewInstanceCreated(userContext, accountSet);
			return present(userContext,retailStoreCountryCenter, mergedAllTokens(tokensExpr));
		}
```

看起来代码里有很多地方都用了这样的模板，能不能解释一下为什么这么用synbchronized，以及里面的这个注释是什么意思。

**Comment by philipgreat** [comment]
如果直接从数据库里面装载，那么这个对象就是一个独立的对象，那么用synchronized确实没有什么用；但，我们的目标是建立平台，所以，如果DAO或者被重写，而使用内存对象的时候，这个就有作用了。

**Comment by xiaodongzhang97** [comment]
> 如果直接从数据库里面装载，那么这个对象就是一个独立的对象，那么用synchronized确实没有什么用；但，我们的目标是建立平台，所以，如果DAO或者被重写，而使用内存对象的时候，这个就有作用了。

 thx

**Comment by philipgreat** [comment]
Question  answered, close.
